name: Build Workflow for tk_date_entry

on:
   push:
     tags:
       - "v*.*.*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0  # Fetch all history for accurate commits and tags

      - name: Update VERSION in __version__.py; commit and push updates
        run: |
          $filePath = "tk_date_entry/__version__.py"
          $VERSION = "${{ github.ref_name }}"
          if ($VERSION.StartsWith('v')) {
              $VERSION = $VERSION.Substring(1)
          }
          (Get-Content $filePath) -replace '^__version__ = ".*"$', "__version__ = `"$VERSION`"" | Set-Content $filePath
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${GITHUB_USER}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add $filePath
          git commit -m "Update VERSION to ${{ github.ref_name }}"
          git push origin main

      - name: Install Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install Python Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Create wrapper
        run: |
          echo "import sys
          import tkinter as tk
          from tk_date_entry import DateEntry

          root = tk.Tk()
          root.title('tk_date_entry demo v' + __import__('tk_date_entry').__version__)
          de = DateEntry(root, date_pattern='%Y-%m-%d')
          de.pack(padx=20, pady=20)
          root.mainloop()" > tk_date_entry_demo.py
        shell: pwsh

      - name: Run PyInstaller to produce the exe file
        run: |
          python -m PyInstaller --onefile tk_date_entry_demo.py --name tk_date_entry --collect-all tk_date_entry

      - name: Zip the tk_date_entry.exe asset to tk_date_entry.zip
        run: |
          Compress-Archive dist/tk_date_entry.exe dist/tk_date_entry.zip
        shell: pwsh

      - name: Generate Changelog
        run: >
          echo "The *tk_date_entry.exe* demo executable file in the
          *tk_date_entry.zip* archive within the assets below is
          auto-generated by a [GitHub Action](.github/workflows/build.yml).
          <br /><br />
          Check the
          [History of modifications](https://github.com/Ircama/tk_date_entry/commits/main/).
          "
          > ${{ github.workspace }}-CHANGELOG.txt

      - name: Create Release, uploading the tk_date_entry.zip asset
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: dist/tk_date_entry.zip
          append_body: true
          generate_release_notes: false

      - name: Remove old releases
        uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 1
          keep-old-minor-releases: false
          keep-old-minor-releases-count: 1
          remove-tags: true
